require_relative('../models/category')
require_relative('../models/manufacturer')
require_relative('../models/product')
require_relative('../models/stock')

category1 = Category.new('name' => 'Road')
category1.save()
category2 = Category.new('name' => 'Gravel')
category2.save()
category3 = Category.new('name' => 'Hardtail')
category3.save()
